server:
  port:  1111
eureka:
  instance:
  #主机名
    hostname: peer1
  client:
    serviceUrl:
    #注册中心地址，把自己注册到注册中心，同时从注册中心同步信息
      defaultZone:  http://peer2:1112/eureka
  # 关闭安全检查
  server:
    enable-self-preservation: false