server:
  port:  1111
eureka:
  instance:
    hostname: localhost
  client:
# 禁止把自己注册到注册中心
    register-with-eureka: false
# 禁止从注册中心检索服务
    fetch-registry: false
#spring:
#  profiles:
#    active: peer1